### ISSUE TITLE
可以加入购物车但是不能下单

### ISSUE THREAD

**Issue by hust-nj** [zstu-lly/JD_Robot#12]
{"reqInfo":null,"hasJxj":false,"addedServiceList":null,"overSea":false,"orderXml":null,"cartXml":null,"noStockSkuIds":"","sign":null,"pin":null,"needCheckCode":true,"success":false,"resultCode":0,"orderId":0,"submitSkuNum":0,"deductMoneyFlag":0,"goJumpOrderCenter":false,"payInfo":null,"scaleSkuInfoListVO":null,"purchaseSkuInfoListVO":null,"noSupportHomeServiceSkuList":null,"msgMobile":null,"addressVO":null,"msgUuid":null,"message":"验证码不正确，请重新填写"}                  下单失败！<0: 验证码不正确，请重新填写>

**Comment by zstu-lly** [comment]
> {"reqInfo":null,"hasJxj":false,"addedServiceList":null,"overSea":false,"orderXml":null,"cartXml":null,"noStockSkuIds":"","sign":null,"pin":null,"needCheckCode":true,"success":false,"resultCode":0,"orderId":0,"submitSkuNum":0,"deductMoneyFlag":0,"goJumpOrderCenter":false,"payInfo":null,"scaleSkuInfoListVO":null,"purchaseSkuInfoListVO":null,"noSupportHomeServiceSkuList":null,"msgMobile":null,"addressVO":null,"msgUuid":null,"message":"验证码不正确，请重新填写"} 下单失败！<0: 验证码不正确，请重新填写>

请提供一下你要下单商品的sku

**Comment by hust-nj** [comment]
> > {"reqInfo":null,"hasJxj":false,"addedServiceList":null,"overSea":false,"orderXml":null,"cartXml":null,"noStockSkuIds":"","sign":null,"pin":null,"needCheckCode":true,"success":false,"resultCode":0,"orderId":0,"submitSkuNum":0,"deductMoneyFlag":0,"goJumpOrderCenter":false,"payInfo":null,"scaleSkuInfoListVO":null,"purchaseSkuInfoListVO":null,"noSupportHomeServiceSkuList":null,"msgMobile":null,"addressVO":null,"msgUuid":null,"message":"验证码不正确，请重新填写"} 下单失败！<0: 验证码不正确，请重新填写>
> 
> 请提供一下你要下单商品的sku

https://item.jd.com/27663487221.html

**Comment by zstu-lly** [comment]
> > > {"reqInfo":null,"hasJxj":false,"addedServiceList":null,"overSea":false,"orderXml":null,"cartXml":null,"noStockSkuIds":"","sign":null,"pin":null,"needCheckCode":true,"success":false,"resultCode":0,"orderId":0,"submitSkuNum":0,"deductMoneyFlag":0,"goJumpOrderCenter":false,"payInfo":null,"scaleSkuInfoListVO":null,"purchaseSkuInfoListVO":null,"noSupportHomeServiceSkuList":null,"msgMobile":null,"addressVO":null,"msgUuid":null,"message":"验证码不正确，请重新填写"} 下单失败！<0: 验证码不正确，请重新填写>
> > 
> > 
> > 请提供一下你要下单商品的sku
> 
> https://item.jd.com/27663487221.html

换一个账号下单看看，换一个商品下单看看

**Comment by hust-nj** [comment]
> > > > {"reqInfo":null,"hasJxj":false,"addedServiceList":null,"overSea":false,"orderXml":null,"cartXml":null,"noStockSkuIds":"","sign":null,"pin":null,"needCheckCode":true,"success":false,"resultCode":0,"orderId":0,"submitSkuNum":0,"deductMoneyFlag":0,"goJumpOrderCenter":false,"payInfo":null,"scaleSkuInfoListVO":null,"purchaseSkuInfoListVO":null,"noSupportHomeServiceSkuList":null,"msgMobile":null,"addressVO":null,"msgUuid":null,"message":"验证码不正确，请重新填写"} 下单失败！<0: 验证码不正确，请重新填写>
> > > 
> > > 
> > > 请提供一下你要下单商品的sku
> > 
> > 
> > https://item.jd.com/27663487221.html
> 
> 换一个账号下单看看，换一个商品下单看看

换了个商品就成功了，没有这个问题

**Comment by zstu-lly** [comment]
> > > > > {"reqInfo":null,"hasJxj":false,"addedServiceList":null,"overSea":false,"orderXml":null,"cartXml":null,"noStockSkuIds":"","sign":null,"pin":null,"needCheckCode":true,"success":false,"resultCode":0,"orderId":0,"submitSkuNum":0,"deductMoneyFlag":0,"goJumpOrderCenter":false,"payInfo":null,"scaleSkuInfoListVO":null,"purchaseSkuInfoListVO":null,"noSupportHomeServiceSkuList":null,"msgMobile":null,"addressVO":null,"msgUuid":null,"message":"验证码不正确，请重新填写"} 下单失败！<0: 验证码不正确，请重新填写>
> > > > 
> > > > 
> > > > 请提供一下你要下单商品的sku
> > > 
> > > 
> > > https://item.jd.com/27663487221.html
> > 
> > 
> > 换一个账号下单看看，换一个商品下单看看
> 
> 换了个商品就成功了，没有这个问题

好的
