### ISSUE TITLE
没有购物车链接 ，运行出错

### ISSUE THREAD

**Issue by cg-llc** [zstu-lly/JD_Robot#13]
您好，作者，运行错误如下：
Tue Feb 18 16:45:01 2020 > 商品详情
编号：100006391078                                                                                                      
库存：现货                                                                                                              
价格：2399.00                                                                                                           
名称：                                                                                                                  
加入购物车链接：                                                                                                        
没有购物车链接    
MainThread - ERROR - 259 - good_detail - 'NoneType' object has no attribute 'text'

**Comment by cg-llc** [comment]
> 您好，作者，运行错误如下：
> 2020年2月18日星期二>商品详情
> 编号：100006391078
> 库存：现货
> 价格：2399.00
> 名称：
> 加入购物车链接：
> 没有购物车链接
> MainThread-错误-259-good_detail-' NoneType'对象没有属性'text'

**Comment by lf1029698952** [comment]
想问下，是如何解决的？

**Comment by cg-llc** [comment]
> 想问下，是如何解决的？

你好，请检查代码中bs4相关的代码行，debug发现bs4代码所在行代码请求的网页内容无法解析或者缺失

**Comment by lf1029698952** [comment]
了解了，谢谢
