### ISSUE TITLE
扫码登录不能使用

### ISSUE THREAD

**Issue by lmx920014697** [zstu-lly/JD_Robot#16]
扫码登录不能使用，京东app识别不了的

**Comment by zstu-lly** [comment]
> 扫码登录不能使用，京东app识别不了的

主题背景是否是黑色的

**Comment by lmx920014697** [comment]
> > 扫码登录不能使用，京东app识别不了的
> 
> 主题背景是否是黑色的

是黑色的，但是京东的客户端没有任何反应。

**Comment by zstu-lly** [comment]
> > > 扫码登录不能使用，京东app识别不了的
> > 
> > 
> > 主题背景是否是黑色的
> 
> 是黑色的，但是京东的客户端没有任何反应。

换成白色
