### ISSUE TITLE
您好，查库存的网址似乎不能用了

### ISSUE THREAD

**Issue by XuXShirley** [zstu-lly/JD_Robot#2]
报错如下：
2019-09-25 23:10:37,320 - MainThread - ERROR - 230 - good_stock - Expecting value: line 1 column 1 (char 0)

print(response.text)输出了403 Forbidden等内容

**Comment by zstu-lly** [comment]
请你提供一下商品的sku

**Comment by XuXShirley** [comment]
> 请你提供一下商品的sku

用的代码里test的那个 options.good = '49272463149'

**Comment by zstu-lly** [comment]
有空的时候我修复下

**Comment by XuXShirley** [comment]
好的，谢谢

**Comment by zstu-lly** [comment]
请删掉cookie之后重新尝试一下，我晚上试了一下又可以下单了，你可以把原来的代码删掉，重新clone我刚刚改过的代码进行测试
