### ISSUE TITLE
每天需要重新扫码登陆

### ISSUE THREAD

**Issue by alpha19976** [zstu-lly/JD_Robot#3]
您好，每隔24小时需要重新扫码登陆，否则会出现如下错误：

Tue Jan 28 21:59:31 2020 > 商品详情
编号：1973984
库存：现货
价格：9.90
名称：金沙河面条 香菇挂面 1kg
加入购物车链接：http://cart.jd.com/gate.action?pid=1973984&pcount=1&ptype=1
商品已成功加入购物车！
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Tue Jan 28 21:59:35 2020 > 订单详情
Traceback (most recent call last):
  File ".\spidertest.py", line 553, in <module>
    while not spider.buy(options) and options.flush:
  File ".\spidertest.py", line 332, in buy
    return self.order_info(options.submit)
  File ".\spidertest.py", line 374, in order_info
    payment = soup.find(id='sumPayPriceId').text    # TODO
AttributeError: 'NoneType' object has no attribute 'text'
PS D:\github\JD_Robot-master>

**Comment by zstu-lly** [comment]
因为cookie过期了吧，所以没办法
