### ISSUE TITLE
一直输出 没有购物车链接，怎么解决？

### ISSUE THREAD

**Issue by loadinL** [zstu-lly/JD_Robot#7]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Wed Feb  5 01:56:55 2020 > 商品详情
编号：1537945
库存：现货
价格：19.90
名称：
加入购物车链接：
没有购物车链接
2020-02-05 01:56:57,085 - MainThread - ERROR - 259 - good_detail - 'NoneType' object has no attribute 'text'
+++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by zstu-lly** [comment]
购物车清空一下

**Comment by HareKrish** [comment]
我也碰到一样的问题了，上午还可以用，到晚上就一直没有购物车链接了。。。。。清空购物车也没用

**Comment by zstu-lly** [comment]
清理一下cookie
